export const paths = {
  home: '/',
  design_shoe: '/design_your_shoe',
  design_bag: '/design_your_bag',
  ready_made_products: '/ready_made_products',
  accessories: '/accessories',
  shoe_care_product: '/shoe_care_product',
  customer_experience: '/customer_experience',
  about: '/about',
  cookies: '/cookies',
  accountDetails: '/account/details',
  myOrders: '/account/my_orders',
  designList: '/account/design_list',
  shippingAddress: '/account/shipping_address',
  changePassword: '/account/change_password',
  reviews: '/account/reviews',
};
