export const paths = {
  home: '/',
  design_shoe: '/design_your_shoe',
  design_bag: '/design_your_bag',
  ready_made_products: '/ready_made_products',
  accessories: '/accessories',
  shoe_care_product: '/shoe_care_product',
  customer_experience: '/customer_experience',
  about: '/about',
  cookies: '/cookies',
  account: '/account/*',
  accountDetails: 'details',
  myOrders: 'my_orders',
  designList: 'design_list',
  shippingAddress: 'shipping_address',
  changePassword: 'change_password',
  reviews: 'reviews',
};
